server:
  port: 8081  # 设置服务器端口为 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/111
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml  # 指定Mapper XML文件的位置