server:
  port: 8081  # 设置服务器端口为 8081

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/mydb  # 数据库连接 URL
#    username: root  # 数据库用户名
#    password: password  # 数据库密码
#    driver-class-name: com.mysql.cj.jdbc.Driver  # 数据库驱动类名